# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle


name: CI - build and test

on:                                
  push:
    branches: [ CBranch ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2        
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew    

      - name: Clean Build
        run: ./gradlew clean

      - name: Build and test
        run: ./gradlew build
      
      - name: Modify reports files
        run: ./gradlew modifyReportsFiles

      - name: Deploy Website
        run: ./gradlew reports

      - name: Generate data graphs
        run: ./gradlew reportStats

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          clean-exclude: |
            index.md
            _config.yml
            README.md
            .gitignore
